version: '3.8'

services:
  
  postgres-tenant:
    container_name: poc-tenant-postgres
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
